import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import Link from 'next/link'
import AuthButton from '@/components/auth-button/auth-button'

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
})
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <nav>
                    <div className="flex justify-between gap-6 w-full text-white">
                        <div className="flex gap-6">
                            <Link href="/">Home</Link>
                            <Link href="/private">Private</Link>
                        </div>
                        <AuthButton />
                    </div>
                </nav>
                {children}
            </body>
        </html>
    )
}
